create table spar.seedlot (
  seedlot_number                  varchar(5) not null,
  seedlot_status_code             varchar(3) not null,
  applicant_client_number         varchar(8),
  applicant_locn_code             varchar(2),
  applicant_email_address         varchar(100),
  vegetation_code                 varchar(8),
  genetic_class_code              varchar(1),
  seedlot_source_code             varchar(3),
  to_be_registrd_ind              boolean,
  bc_source_ind                   boolean,
  collection_client_number        varchar(8),
  collection_locn_code            varchar(2),
  collection_start_date           timestamp,
  collection_end_date             timestamp,
  no_of_containers                decimal(6, 2),
  vol_per_container               decimal(6, 2),
  clctn_volume                    decimal(6, 2),
  seedlot_comment                 varchar(2000),
  interm_strg_client_number       varchar(8),
  interm_strg_locn_code           varchar(2),
  interm_strg_st_date             timestamp,
  interm_strg_end_date            timestamp,
  interm_facility_code            varchar(3),
  female_gametic_mthd_code        varchar(4),
  male_gametic_mthd_code          varchar(4),
  controlled_cross_ind            boolean,
  biotech_processes_ind           boolean,
  pollen_contamination_ind        boolean,
  pollen_contamination_pct        int,
  contaminant_pollen_bv           decimal(4, 1),
  pollen_contamination_mthd_code  varchar(4),
  total_parent_trees              int,
  smp_success_pct                 int,
  effective_pop_size              decimal(5, 1),
  tested_parent_tree_cont_pct     decimal(6, 2),
  coancestry                      decimal(20, 10),
  smp_parents_outside             int,
  non_orchard_pollen_contam_pct   int,
  extractory_client_number        varchar(8),
  extractory_locn_code            varchar(2),
  extraction_st_date              timestamp,
  extraction_end_date             timestamp,
  storage_client_number           varchar(8),
  storage_locn_code               varchar(2),
  temporary_storage_start_date    timestamp,
  temporary_storage_end_date      timestamp,
  declared_userid                 varchar(30),
  declared_timestamp              timestamp,
  entry_userid                    varchar(30) not null,
  entry_timestamp                 timestamp not null,
  update_userid                   varchar(30) not null,
  update_timestamp                timestamp not null,
  revision_count                  int not null,
  constraint seedlot_pk
    primary key(seedlot_number)
);
