apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nr-spar-backend
  annotations:
    description: "NR SPAR Database"
    tags: "nr-spar-backend,database"
    iconClass: icon-java
labels:
  app: nr-spar-backend-test
  app.kubernetes.io/part-of: nr-spar-backend-test
parameters:
  - name: NAME
    description: Product name
    value: nr-spar-backend
  - name: COMPONENT
    description: Component name
    value: database
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: IMAGE_TAG
    description: Image tag to use
    value: latest
  - name: PVC_MOUNT_PATH
    description: Where to mount the PVC, subpath (e.g. data/)
    value: /var/lib/postgresql
  - name: DB_PVC_SIZE
    description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Database Volume Capacity
    required: true
    value: 256Mi
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: PROMOTE
    description: Image (namespace/name:tag) to promote/import
    required: true
objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: nr-spar-backend-test-database
      labels:
        app: nr-spar-backend-test
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 512Mi
      storageClassName: netapp-file-standard
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: nr-spar-backend-test-database
      labels:
        app: nr-spar-backend-test
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: ghcr.io/bcgov/nr-spar-backend/database:test
          referencePolicy:
            type: Local
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: nr-spar-backend-test-database
      labels:
        app: nr-spar-backend-test
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - nr-spar-backend
            from:
              kind: ImageStreamTag
              name: nr-spar-backend-test-database:latest
      selector:
        deploymentconfig: nr-spar-backend-test-database
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        activeDeadlineSeconds: 21600
      template:
        metadata:
          name: nr-spar-backend-test-database
          labels:
            app: nr-spar-backend-test
            deploymentconfig: nr-spar-backend-test-database
        spec:
          volumes:
            - name: nr-spar-backend-test-database
              persistentVolumeClaim:
                claimName: nr-spar-backend-test-database
          containers:
            - name: nr-spar-backend
              image: nr-spar-backend-test-database:latest
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /usr/bin/env
                    - bash
                    - '-c'
                    - psql -q -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'
                failureThreshold: 5
                initialDelaySeconds: 30
                periodSeconds: 15
                timeoutSeconds: 1
              livenessProbe:
                exec:
                  command:
                    - /usr/bin/env
                    - bash
                    - '-c'
                    - psql -q $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'
                failureThreshold: 5
                initialDelaySeconds: 30
                periodSeconds: 15
                timeoutSeconds: 1
              env:
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: nr-spar-backend-test-database
                      key: database-name
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: nr-spar-backend-test-database
                      key: database-password
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: nr-spar-backend-test-database
                      key: database-user
              volumeMounts:
                - name: nr-spar-backend-test-database
                  mountPath: /var/lib/postgresql
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          schedulerName: default-scheduler
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: nr-spar-backend-test
      name: nr-spar-backend-test-database
    spec:
      ports:
        - name: postgresql
          nodePort: 0
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        deploymentconfig: nr-spar-backend-test-database
      sessionAffinity: None
      type: ClusterIP
